# -*- coding: utf-8 -*-
"""MLPATTERNS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9QcFZFPwqfpLYLNWrqIK2UsWL8GS7-W
"""

pip install fyers_apiv3 pandas_ta_classic #autogluon

from fyers_apiv3 import fyersModel
import pandas as pd
from datetime import date
import numpy as np
import pandas_ta_classic as ta
import numpy as np
import pandas as pd
import pandas as pd
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
pd.set_option('display.max_columns', None)



client_id = "OKWRSZLNMI-100"
secret_key = "ONC1CLURVV"
redirect_uri = "https://iamshiv.com/"
response_type = "code"
state = "sample_state"

session = fyersModel.SessionModel(
    client_id=client_id,
    secret_key=secret_key,
    redirect_uri=redirect_uri,
    response_type=response_type
)
response = session.generate_authcode()
print('open this url and paste authcode in input : ',response)
auth_code = input('enter auth code here ________')
session = fyersModel.SessionModel(
    client_id=client_id,
    secret_key=secret_key,
    redirect_uri=redirect_uri,
    response_type=response_type,
    grant_type="authorization_code"
)
session.set_token(auth_code)
response = session.generate_token()
print(response)

today = date.today().strftime("%Y-%m-%d")
client_id = "OKWRSZLNMI-100"
# access_token = response['access_token']
access_token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIl0sImF0X2hhc2giOiJnQUFBQUFCcUdrNmtuYkVHRGZLNDQtMWdhVW5RZE92WV8zWEpBWG5LblIyaC0wZFJwc1NNaldZUnpaR1NVcF9OUU9SWUlVekVWWXRVTkc2UVNZZ0JGN1lIcU85ckFkcGRvN0xmR2tYTWxSZXR2dGtXM09nY1FLMD0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI5MTU5OTZmMjU1ZTk5NmI1ZWM5OGQ2M2E1ZjBkNGRiOWEzNDcyMWEzN2IwZmRlNGQxOGQxN2FmZiIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiRFMwMTAyMSIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzgwMTg3NDAwLCJpYXQiOjE3ODAxMDg5NjQsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc4MDEwODk2NCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.CXMxcJsvJea5ee4gQs3MJ1vfkATgyydga_XLrhz3bHM'
fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=access_token, log_path="")
fyers.get_profile()

from datetime import datetime, timedelta
def fetch_historical_data_in_chunks(fyers, symbol, resolution, start_date, end_date, chunk_days=100):
        start = datetime.strptime(start_date, "%Y-%m-%d")
        end = datetime.strptime(end_date, "%Y-%m-%d")

        all_data = []
        current_start = start

        while current_start < end:
            # Calculate chunk end date (max 100 days from current_start)
            current_end = min(current_start + timedelta(days=chunk_days-1), end)

            # Format dates for API
            range_from = current_start.strftime("%Y-%m-%d")
            range_to = current_end.strftime("%Y-%m-%d")

            print(f"Fetching data from {range_from} to {range_to}...")

            # Fetch data for this chunk
            data = {
                "symbol": symbol,
                "resolution": resolution,
                "date_format": "1",
                "range_from": range_from,
                "range_to": range_to,
                "cont_flag": "1"
            }

            response = fyers.history(data=data)

            # Check if response is successful
            if response.get('s') == 'ok' and 'candles' in response:
                chunk_df = pd.DataFrame(response['candles'])
                if not chunk_df.empty:
                    all_data.append(chunk_df)
            else:
                print(f"Error fetching data: {response}")

            # Move to next chunk
            current_start = current_end + timedelta(days=1)

        # Combine all chunks
        if all_data:
            combined_df = pd.concat(all_data, ignore_index=True)

            # Apply column names and datetime conversion
            cols = ['datetime', 'open', 'high', 'low', 'close', 'volume']
            combined_df.columns = cols
            combined_df['datetime'] = pd.to_datetime(combined_df['datetime'], unit="s")
            combined_df['datetime'] = combined_df['datetime'].dt.tz_localize('utc').dt.tz_convert('Asia/Kolkata')
            combined_df['datetime'] = combined_df['datetime'].dt.tz_localize(None)

            # Remove duplicates (in case of overlapping data)
            combined_df = combined_df.drop_duplicates(subset=['datetime']).reset_index(drop=True)

            return combined_df
        else:
            return pd.DataFrame()
symbol = 'TCS'
df = fetch_historical_data_in_chunks( fyers, f'NSE:{symbol}-EQ', '5', '2023-05-26', today, chunk_days=100) # 1D for day 5 only for mins
# df['stock_name'] = symbol
# df = (df.sort_values("datetime").drop_duplicates(subset=["datetime"], keep="last").reset_index(drop=True))
# df.set_index('datetime', inplace=True)
df

df['hour'] = pd.to_datetime(df['datetime']).dt.hour
df['minute'] = pd.to_datetime(df['datetime']).dt.minute
df.drop(columns=['datetime'],inplace=True)
df

# final version
def add_technical_indicators(df):
    df["body_pct"] = ((df["close"] - df["open"]) / df["open"]) * 100 # Candle Body %
    df["range_pct"] = ((df["high"] - df["low"]) / df["open"]) * 100 # Candle Range %
    df["upper_wick_pct"] = ((df["high"] - np.maximum(df["open"], df["close"]))/ df["open"]) * 100 # Upper Wick %
    df["lower_wick_pct"] = ((np.minimum(df["open"], df["close"]) - df["low"])/ df["open"]) * 100 # Lower Wick %
    df["candle_direction"] = np.where(df["close"] > df["open"],1,np.where(df["close"] < df["open"], -1, 0)) # Candle Direction1 = Bullish -1 = Bearish  0 = Neutral
    df["hlc3"] = (df["high"] +df["low"] +df["close"]) / 3 # HLC3 = (High + Low + Close) / 3
    df["ohlc4"] = (df["open"] +df["high"] +df["low"] +df["close"]) / 4 # OHLC4 = (Open + High + Low + Close) / 4
    df["gap_pct"] = ((df["open"] - df["close"].shift(1))/ df["close"].shift(1)) * 100 # Gap % Current Open vs Previous Close
    df['ema_9'] = df.ta.ema(9)
    df['ema_20'] = df.ta.ema(20)
    df['ema_50'] = df.ta.ema(50)
    df["close_ema9_dist"] = ((df["close"] - df["ema_9"]) / df["ema_9"]) * 100 # Distance of Close from EMA 9
    df["close_ema20_dist"] = ((df["close"] - df["ema_20"]) / df["ema_20"]) * 100 # Distance of Close from EMA 20
    df["close_ema50_dist"] = ((df["close"] - df["ema_50"]) / df["ema_50"]) * 100 # Distance of Close from EMA 50
    df["ema9_above_20"] = (df["ema_9"] > df["ema_20"]).astype(int) # EMA 9 above EMA 20
    df["ema20_above_50"] = (df["ema_20"] > df["ema_50"]).astype(int) # EMA 20 above EMA 50
    df['rsi_14'] = df.ta.rsi(length=14)
    macd = df.ta.macd(fast=12, slow=26, signal=9)
    df['macd'] = macd['MACD_12_26_9']
    df['macd_hist'] = macd['MACDh_12_26_9']
    df['macd_signal'] = macd['MACDs_12_26_9']
    df['roc_10'] = df.ta.roc(length=10)
    stoch = df.ta.stoch(fast_k=14, slow_k=3, slow_d=3)
    df['stoch_k'] = stoch.iloc[:, 0]
    df['stoch_d'] = stoch.iloc[:, 1]
    df['volume_sma_20'] = df['volume'].rolling(20).mean() # Volume
    df['rvol'] = df['volume'] / df['volume'].rolling(14).mean() # Manual RVOL
    df['volume_spike'] = (df['volume'] > df['volume'].rolling(10).mean() * 1.5).astype(int) # Best balance for most traders
    df['obv'] = df.ta.obv()
    df['cmf'] = df.ta.cmf(length=14)
    df['atr_14'] = df.ta.atr(length=14) # Volatility
    bb = df.ta.bbands(length=20)
    df['bb_lower'] = bb['BBL_20_2.0']
    df['bb_middle'] = bb['BBM_20_2.0']
    df['bb_upper'] = bb['BBU_20_2.0']
    df['bb_width'] = bb['BBB_20_2.0'] # Bollinger Band Width
    df['bb_percent'] = bb['BBP_20_2.0'] # Bollinger Band Position
    # df['vwap'] = df.ta.vwap() # VWA
    # df['close_vwap_dist'] = ((df['close'] - df['vwap']) / df['vwap']) * 100 # Distance from VWAP
    df['rolling_high_20'] = (df['high'].rolling(20).max()) # Previous 20 candle highest high
    df['rolling_low_20'] = (df['low'].rolling(20).min()) # Previous 20 candle lowest low
    df['prev_high_break'] = (df['close'] >df['rolling_high_20'].shift(1)).astype(int) # Current close breaks previous rolling high
    df['prev_low_break'] = (df['close'] <df['rolling_low_20'].shift(1)).astype(int) # Current close breaks previous rolling low
    df['inside_bar'] = ((df['high'] < df['high'].shift(1)) &(df['low'] > df['low'].shift(1))).astype(int)  # Inside Bar Current candle inside previous candle range
    df['outside_bar'] = ((df['high'] > df['high'].shift(1)) &(df['low'] < df['low'].shift(1))).astype(int) # Outside Bar  Current candle engulfs previous candle range
    green = (df['close'] > df['open']).astype(int) # Green Candle
    red = (df['close'] < df['open']).astype(int) # Red Candle
    df['consecutive_green'] = (green.groupby((green != green.shift()).cumsum()).cumsum()) # Consecutive Green Candles
    df['consecutive_red'] = (red.groupby((red != red.shift()).cumsum()).cumsum()) # Consecutive Red Candles
    future_period = 5

    df['future_max_high'] = (
        df['high']
        .rolling(future_period)
        .max()
        .shift(-future_period)
    )
    df['future_max_return'] = (
    (df['future_max_high'] - df['close'])
    / df['close']
    ) * 100

    df['atr_pct'] = (
        df['atr_14'] / df['close']
    ) * 100
    df['future_close'] = (df['close'].shift(-future_period))
    df['future_return'] = ((df['future_close'] - df['close'])/ df['close']) * 100
    df['future_min_low'] = (df['low'].rolling(future_period).min().shift(-future_period))
    df['future_min_return'] = ((df['future_min_low'] - df['close'])/ df['close']) * 100
    atr_multiplier = 0.5
    df['dynamic_threshold'] = (df['atr_pct']* atr_multiplier)
    df['target'] = (df['future_return']> df['dynamic_threshold']).astype(int)
    # patterns = df.ta.cdl_pattern(name="all")
    # df = pd.concat([df, patterns], axis=1)
    df.dropna(inplace=True)
    df['target'] = (df['future_max_return'] > (df['atr_pct'] * 0.75)).astype(int)

    return df

# tcs_df = add_technical_indicators(df)

df = add_technical_indicators(df)
df

df.head()

"""To display all columns in a pandas DataFrame without truncation, you can set the `display.max_columns` option to `None`."""

drop_cols = [
    'future_close',
    'future_return',
    'future_max_high',
    'future_max_return',
    'future_min_low',
    'future_min_return',
    'dynamic_threshold',
    'target'
]
X = df.drop(columns=drop_cols)

y = df['target']
print("X Shape:", X.shape)
print("y Shape:", y.shape)
print(y.value_counts(normalize=True))




from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,shuffle=False)

# ============================================================
# CREATE MODEL
# ============================================================
scale_pos_weight = (
    (y_train == 0).sum() /
    (y_train == 1).sum()
)
model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

# ============================================================
# TRAIN MODEL
# ============================================================

model.fit(X_train, y_train)

print("Model Training Completed")
# ============================================================
# PREDICTIONS
# ============================================================

y_pred = model.predict(X_test)

# ============================================================
# EVALUATION
# ============================================================

print("Accuracy:")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
# ============================================================
# PREDICTION PROBABILITIES
# ============================================================

y_proba = model.predict_proba(X_test)[:, 1]

# ============================================================
# RESULTS DATAFRAME
# ============================================================

results = pd.DataFrame({
    'actual': y_test.values,
    'probability': y_proba
})

print(results.head())

# ============================================================
# THRESHOLD TESTING
# ============================================================

thresholds = [0.60, 0.65, 0.70, 0.75, 0.80]

for t in thresholds:

    temp = results[results['probability'] > t].copy()

    temp['pred'] = 1

    precision = (temp['actual'] == temp['pred']).mean()

    print(f"\nThreshold: {t}")
    print("Signals :", len(temp))
    print("Precision:", precision)
# ============================================================
# CREATE RESULTS DATAFRAME
# ============================================================

results = X_test.copy()

results['actual'] = y_test.values

results['probability'] = y_proba


# ============================================================
# SIGNALS
# ============================================================

threshold = 0.75

results['signal'] = ( results['probability'] > threshold).astype(int)


# ============================================================
# ENTRY PRICE
# ============================================================

results['entry_price'] = (results['open'].shift(-1))


# ============================================================
# ATR VALUES
# ============================================================

results['atr'] = results['atr_14']


# ============================================================
# STOPLOSS & TARGET
# ============================================================

results['stoploss'] = (results['entry_price']- results['atr'])

results['target_price'] = ( results['entry_price'] + (2 * results['atr']))


# ============================================================
# TRADE SIMULATION
# ============================================================

holding_period = 5

trade_results = []

for idx in results.index:

    row = results.loc[idx]

    # Only signals
    if row['signal'] != 1:
        continue

    entry = row['entry_price']
    sl = row['stoploss']
    tp = row['target_price']


    # Get the position of idx
    pos = results.index.get_loc(idx)

    # Use iloc with position-based slicing
    future_data = results.iloc[pos : pos + holding_period]

    trade_exit = None

    for _, candle in future_data.iterrows():

        high = candle['high']
        low = candle['low']

        # Stoploss hit
        if low <= sl:
            trade_exit = sl
            break

        # Target hit
        elif high >= tp:
            trade_exit = tp
            break

    # Timeout exit
    if trade_exit is None:
        trade_exit = future_data.iloc[-1]['close']

    # Trade Return
    trade_return = ((trade_exit - entry)/ entry) * 100

    trade_results.append({
        'entry': entry,
        'exit': trade_exit,
        'return_pct': trade_return
    })


# ============================================================
# TRADES DATAFRAME
# ============================================================

trades = pd.DataFrame(trade_results)


# ============================================================
# PERFORMANCE METRICS
# ============================================================

if len(trades) > 0:

    print("Total Trades:", len(trades))

    print("Win Rate:",
          (trades['return_pct'] > 0).mean())

    print("Average Return:",
          trades['return_pct'].mean())
    print("Average Win:",trades.loc[    trades['return_pct'] > 0,    'return_pct'].mean())

    print("Average Loss:",trades.loc[    trades['return_pct'] <= 0,    'return_pct'].mean())

    # ============================================================
    # EQUITY CURVE
    # ============================================================

    trades['equity_curve'] = (trades['return_pct'].cumsum())

    print(trades.head())

else:

    print("No trades generated.")